ORG 1000H
X DB 3
TABLA DB ?

ORG 2000H
MOV AX, 0
MOV CX, 0
MOV BX, OFFSET TABLA
MOV CL, X ; GUARDO X EN BL
LOOP: MOV AL, CL ; GUARDO BL EN AL PARA COMPROBAR SI ES PAR O NO ES PAR
LOOPA: SUB AL, 2 ; VOY RESTANDO 2
JNS LOOPA ; SI NO ES NEGATIVO EL RESULTADO, VUELVO AL LOOP
NEG AL ; UNA VEZ QUE FUE NEGATIVO, LO PASO A POSITIVO
CMP AL, 2 ; LO COMPARO CON 2
JZ ESPAR ; SI 2-2 = 0 ENTONCES SALTO A SI EL NUMERO ES PAR
ADD CL, 5; CUANDO NO ES PAR SE SUMA 5
MOV [BX], CL 
INC BX
CMP CL, 0 ; COMPARO SI EL RESULTADO DESPUES DE SUMARLE 5 ES 0
JZ FIN ; SI ES 0, SALTO AL FINAL DEL PROGRAMA
JMP LOOP ; SI NO ES 0, SALTARA AL LOOP DE NUEVO
ESPAR: SUB CL, 7 ; EN CASO QUE SEA PAR AL NUMERO SE LE SUMARA 7
MOV [BX], CL
INC BX
CMP CL, 0 ;COMPARO CON 0
JZ FIN ; SI ES 0 TERMINO EL PROGRAMA
JMP LOOP ; SI NO ES 0 VUELVO AL LOOP
FIN: HLT
END
